# Site settings
title: The DejaData Blog
email: r.morrisey@computer.org
description: > # this means to ignore newlines until "baseurl:"
  Adventures in software, data science and whatnot.
host: ip-172-31-25-134
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/dejadata.com" # the base hostname & protocol for your site
twitter_username: divcurl
github_username:  4current

# Build settings
markdown: kramdown
